[project]
name = "bobkonf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hypothesis>=6.127.3",
    "requests>=2.32.3",
]
